# platform :ios, '14.0'
platform :ios, '14.0'

plugin_pods = [
  'google_maps_flutter_ios'
]

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # اجبار جميع الـ Pods والـ Plugins يخدموا بـ iOS 14.0 لتفادي أي نزاع ف الـ Versions
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end